# Generated by Django 3.2.3 on 2022-04-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_comment_evaluation_format_lecture_selection_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='price',
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_free',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
