# Generated by Django 3.2.3 on 2022-04-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='appraise_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
